### ISSUE TITLE
Cebu Cities and Bataan Cities are wrong.

### ISSUE THREAD

**Issue by wyrl** [dr5hn/countries-states-cities-database#34]
Country: Philippines

The cities in Cebu is Bataan Cities.

**Comment by dr5hn** [comment]
@wyrl Can you help me to fix it up ?

**Comment by dr5hn** [comment]
@wyrl It should be fixed now with #57. Can you please verify ?

**Comment by dr5hn** [comment]
@wyrl Closing this issue for now. If you feel it still persist, please feel free to reopen.

**Comment by kenth-israel-goteam** [comment]
Hello, it is still not correct.
This is a good reference: https://github.com/clavearnel/philippines-region-province-citymun-brgy

Thank you in advance to whoever will PR this :)
